version: 2.1

executors:
  default:
    working_directory: ~/repo
    docker:
      - image: lambci/lambda:build-nodejs10.x

jobs:
  build:
    executor:
      name: default

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Check coding standard by ESLint
          command: npm run lint

      - run:
          name: Run test
          command: npm run test

      - persist_to_workspace:
          root: ~/repo
          paths:
            - ./*
  deploy-stage:
    executor:
      name: default
    steps:
      - attach_workspace:
          at: ~/repo
      - deploy:
          name: deploy service for dev
          command: npx serverless deploy --stage development
      - deploy:
          name: deploy service for stage
          command: npx serverless deploy --stage staging

  deploy-prod:
    executor:
      name: default
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: deploy production
          command: npx serverless deploy --stage production
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy-stage:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy-prod:
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/